CREATE TABLE IF NOT EXISTS weather_staging (
    id BIGINT IDENTITY(1,1),
    location_name VARCHAR(255),
    region VARCHAR(255),
    country VARCHAR(255),
    lat DECIMAL(8,5),
    lon DECIMAL(8,5),
    tz_id VARCHAR(255),
    localtime_epoch BIGINT,
    local_time TIMESTAMP,
    last_updated_epoch BIGINT,
    last_updated TIMESTAMP,
    temp_c DECIMAL(5,2),
    temp_f DECIMAL(5,2),
    is_day INT,
    condition_text VARCHAR(255),
    wind_mph DECIMAL(5,2),
    wind_kph DECIMAL(5,2),
    wind_degree INT,
    wind_dir VARCHAR(10),
    pressure_mb DECIMAL(6,2),
    precip_mm DECIMAL(5,2),
    humidity INT,
    cloud INT,
    feelslike_c DECIMAL(5,2),
    feelslike_f DECIMAL(5,2),
    dewpoint_c DECIMAL(5,2),
    dewpoint_f DECIMAL(5,2),
    visibility_km DECIMAL(5,2),
    visibility_miles DECIMAL(5,2),
    uv_index DECIMAL(3,1),
    gust_mph DECIMAL(5,2),
    gust_kph DECIMAL(5,2),
    inserted_at TIMESTAMP DEFAULT GETDATE()
);
