CREATE TABLE IF NOT EXISTS weather_staging (
    location_name VARCHAR(255),
    region VARCHAR(255),
    country VARCHAR(255),
    lat DECIMAL(7, 4),
    lon DECIMAL(7, 4),
    tz_id VARCHAR(50),
    localtime_epoch BIGINT,
    local_time TIMESTAMP,
    last_updated_epoch BIGINT,
    last_updated TIMESTAMP,
    temp_c DECIMAL(5, 2),
    temp_f DECIMAL(5, 2),
    is_day BOOLEAN,
    condition_text VARCHAR(255),
    condition_icon VARCHAR(255),
    condition_code INT,
    wind_mph DECIMAL(5, 2),
    wind_kph DECIMAL(5, 2),
    wind_degree INT,
    wind_dir VARCHAR(10),
    pressure_mb DECIMAL(6, 2),
    pressure_in DECIMAL(6, 2),
    precip_mm DECIMAL(6, 2),
    precip_in DECIMAL(6, 2),
    humidity INT,
    cloud INT,
    feelslike_c DECIMAL(5, 2),
    feelslike_f DECIMAL(5, 2),
    windchill_c DECIMAL(5, 2),
    windchill_f DECIMAL(5, 2),
    heatindex_c DECIMAL(5, 2),
    heatindex_f DECIMAL(5, 2),
    dewpoint_c DECIMAL(5, 2),
    dewpoint_f DECIMAL(5, 2),
    visibility_km DECIMAL(5, 2),
    visibility_miles DECIMAL(5, 2),
    uv_index DECIMAL(3, 1),
    gust_mph DECIMAL(5, 2),
    gust_kph DECIMAL(5, 2),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
